packages:
  - frontend
  - studio

ignoredBuiltDependencies:
  - esbuild
  - package-lock-only

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  undici@<6.23.0: '>=6.23.0'
